#!/usr/bin/env bash

set -euo pipefail

REPO_ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/../.." && pwd)"
CONFIG_SCRIPT="${REPO_ROOT}/tools/macos/scripts/EvEJSConfig.sh"
PREPARE_HELPER="${REPO_ROOT}/tools/macos/prepare-offline-client.sh"
STAGE_HELPER="${REPO_ROOT}/tools/macos/stage-offline-client.sh"
INSTALL_CA_HELPER="${REPO_ROOT}/tools/macos/install-local-ca.sh"

if [[ ! -f "$CONFIG_SCRIPT" ]]; then
  echo "[eve.js] Missing config helper: $CONFIG_SCRIPT" >&2
  exit 1
fi

# shellcheck disable=SC1090
. "$CONFIG_SCRIPT"

SOURCE_ROOT="$EVEJS_MAC_SOURCE_ROOT"
RETAIL_ROOT="$EVEJS_MAC_RETAIL_ROOT"
STAGED_BASE="$EVEJS_MAC_STAGED_BASE"
SETTINGS_PROFILE="$EVEJS_MAC_SETTINGS_PROFILE"
SERVER_HOST="$EVEJS_SERVER_HOST"
PROXY_URL="$EVEJS_PROXY_URL"

INSTALL_CA=true
CLEAN_STAGE=true
COPY_RESFILES=false
PLACEBO_BOOT=true

usage() {
  cat <<'EOF'
Usage: bash tools/macos/StartClientSetup.sh [options]

One-shot setup for the macOS staged-client flow. This mirrors the Windows
Client Setup philosophy:
  1. prepare an isolated source copy
  2. build a byte-preserving staged runtime
  3. install the eve.js local CA
  4. save the paths for Play.sh

Options:
  --source-root <dir>      Source-copy destination. Default:
                           ~/Library/Application Support/eve.js/macos/source-client
  --retail-root <dir>      Retail EVE root containing SharedCache. Default:
                           ~/Library/Application Support/EVE Online
  --staged-base <dir>      Base directory for local staged runtimes. Default:
                           ~/Library/Application Support/eve.js/macos/staged-client
  --settings-profile <id>  Client settings profile. Default: EvEJSLocal
  --server-host <host>     Server host passed at launch. Default: 127.0.0.1
  --proxy-url <url>        Local proxy URL passed at launch. Default:
                           http://127.0.0.1:26002
  --copy-resfiles          Fully copy ResFiles into the staged runtime instead
                           of symlinking them to the local source copy.
  --stock-cryptoapi        Stage a byte-preserving stock CryptoAPI runtime
                           instead of the default Mac Placebo boot overlay.
  --no-clean-stage         Reuse the existing staged build directory.
  --skip-install-ca        Skip login-keychain CA trust installation.
  --help                   Show this help text.
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --source-root)
      SOURCE_ROOT="$2"
      shift 2
      ;;
    --retail-root)
      RETAIL_ROOT="$2"
      shift 2
      ;;
    --staged-base)
      STAGED_BASE="$2"
      shift 2
      ;;
    --settings-profile)
      SETTINGS_PROFILE="$2"
      shift 2
      ;;
    --server-host)
      SERVER_HOST="$2"
      shift 2
      ;;
    --proxy-url)
      PROXY_URL="$2"
      shift 2
      ;;
    --copy-resfiles)
      COPY_RESFILES=true
      shift
      ;;
    --stock-cryptoapi)
      PLACEBO_BOOT=false
      shift
      ;;
    --no-clean-stage)
      CLEAN_STAGE=false
      shift
      ;;
    --skip-install-ca)
      INSTALL_CA=false
      shift
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    *)
      echo "[eve.js] Unknown argument: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
done

persist_local_config() {
  local local_config_path="$EVEJS_MAC_LOCAL_CONFIG_PATH"
  local tmp_path=""

  tmp_path="$(mktemp "${local_config_path}.tmp.XXXXXX")"
  {
    echo "#!/usr/bin/env bash"
    echo "# Local macOS EvEJS paths. Generated by StartClientSetup.sh."
    printf 'export EVEJS_MAC_SOURCE_ROOT=%q\n' "$SOURCE_ROOT"
    printf 'export EVEJS_MAC_RETAIL_ROOT=%q\n' "$RETAIL_ROOT"
    printf 'export EVEJS_MAC_STAGED_BASE=%q\n' "$STAGED_BASE"
    printf 'export EVEJS_MAC_STAGED_ROOT=%q\n' "${STAGED_BASE}/current"
    printf 'export EVEJS_MAC_SETTINGS_PROFILE=%q\n' "$SETTINGS_PROFILE"
    printf 'export EVEJS_SERVER_HOST=%q\n' "$SERVER_HOST"
    printf 'export EVEJS_PROXY_URL=%q\n' "$PROXY_URL"
  } >"$tmp_path"
  mv "$tmp_path" "$local_config_path"
  chmod 600 "$local_config_path"
}

stage_args=(
  --source-root "$SOURCE_ROOT"
  --staged-root "$STAGED_BASE"
)

if [[ "$CLEAN_STAGE" == true ]]; then
  stage_args+=(--clean-stage)
fi

if [[ "$COPY_RESFILES" == true ]]; then
  stage_args+=(--copy-resfiles)
fi

if [[ "$PLACEBO_BOOT" == true ]]; then
  stage_args+=(--boot-common-overlay --boot-crypto-pack Placebo --remove-app-bundle-signature)
fi

echo "[eve.js] Preparing canonical source copy..."
bash "$PREPARE_HELPER" --retail-root "$RETAIL_ROOT" --dest "$SOURCE_ROOT"

echo
if [[ "$PLACEBO_BOOT" == true ]]; then
  echo "[eve.js] Building staged runtime with Mac Placebo boot overlay..."
else
  echo "[eve.js] Building byte-preserving staged runtime..."
fi
bash "$STAGE_HELPER" "${stage_args[@]}"

if [[ "$INSTALL_CA" == true ]]; then
  echo
  echo "[eve.js] Installing eve.js CA into the login keychain..."
  bash "$INSTALL_CA_HELPER"
fi

persist_local_config

echo
echo "[eve.js] macOS client setup is complete."
echo "[eve.js] Saved local config: $EVEJS_MAC_LOCAL_CONFIG_PATH"
echo "[eve.js] Source root: $SOURCE_ROOT"
echo "[eve.js] Retail root: $RETAIL_ROOT"
echo "[eve.js] Staged root: ${STAGED_BASE}/current"
echo
echo "[eve.js] Next steps:"
echo "  bash \"$REPO_ROOT/QuickstartServer.sh\""
echo "  bash \"$REPO_ROOT/Play.sh\" --use-captured-session"
